# Site Settings
locale: "tr-TR"
title: "Kemalistler Birliği"
title_separator: "-"
subtitle: "Kemalizm ve Atatürk İlkeleri"
name: "Kemalistler Birliği"
description: "Kemalizm ve Atatürk ilkeleri hakkında bilimsel makaleler ve analizler."
url: "https://kemalistlerbirligi.github.io"
baseurl: ""
repository: "kemalistlerbirligi/kemalistlerbirligi.github.io"
teaser: # path of fallback teaser image
logo: # path of logo image to display in the masthead
masthead_title: # overrides the website title displayed in the masthead

# Site Author
author:
  name: "Kemalistler Birliği"
  avatar: # path of avatar image
  bio: "Kemalizm ve Atatürk ilkeleri üzerine içerik üretiyoruz."
  location: "Türkiye"
  email: # "your-email@example.com"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://kemalistlerbirligi.github.io"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/JC5dZpmhCs"

# Site Footer
footer:
  links:
  

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/Istanbul

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Comments (isteğe bağlı)
comments:
  provider: "disqus"
  disqus:
    shortname: # "your-disqus-shortname"

# SEO Related
google_site_verification:
google_analytics:
bing_site_verification:
yandex_site_verification:
naver_site_verification:

# Social Sharing
twitter:
  username:
facebook:
  username:
  app_id:
  publisher:
og_image: # Open Graph/Twitter default site image

# Analytics
analytics:
  provider: false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id:
    anonymize_ip: # true, false (default)
